### ISSUE TITLE
Can it be used in Raspberry Pi Zero W?

### ISSUE THREAD

**Issue by julayelei** [Yurockkk/Bluetooth-RPi-Python#1]
I was trying to do all this you have developed, which is really cool, in a Raspberry Pi Zero W using Stretch. For some reason it doesn't work. I wanted to know if it is because I'm using a Raspberry Pi Zero W or if it is because of the OS i'm using.
Thanks for taking some time on reading this. Greetings!

**Comment by julayelei** [comment]
Well, I tried again in Raspberry Pi Zero W using Raspbian Jessie and it worked well! I'm trying again using Stretch with the same configs.
I'm using Jessie Lite.

**Comment by julayelei** [comment]
It worked! I'm closing this.

**Comment by Yurockkk** [comment]
@julayelei Sorry for the late response! I got jammed by tons of notifications from other projects and missed this one. I'm glad that it worked for you now 👍
